### PR TITLE
Some Small bug fixes in librelinkup and futher improvements to carelink

### PR DESCRIPTION
**Pull request by AndyLow91**
This still is not working exactly as expected, but no longer returns the authorization error when using librelinkup.

### CODE REVIEW

**Comment by AndyLow91** [comment]
@bewest I've added some further changes tonight, which will hopefully resolve the stale pump data alarm shown when using the carelink connection. It was difficult to fully test this in my dev environment, so please if you can test it out that would be great!

**Comment by bewest** [comment]
Updated to share the same code to adjust treatments (`dateTime` vs `datetime`) as well in https://github.com/nightscout/nightscout-connect/pull/19

**Comment by AndyLow91** [comment]
Medtronic have made another breaking change to their european servers over the last few days, updating the user-agent string in the http header request appears to have solved this. @bewest - If you can merge, that would be awesome!

**Comment by bewest** [comment]
Could you please test if it's needed on fewer endpoints, eg only the ones that absolutely require an html/js engine?
If it does not work, could you please try adding the `nightscout-connect@version` string somewhere inside the longer UA string?  I think it's important that we deny Medtronic the pleasure of plausible deniability and provide traceability back to the source code when there are issues.

**Pull request merged**
